# Generated by Django 2.2.6 on 2019-10-09 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sermonsundayschool',
            name='mp3',
            field=models.FileField(upload_to=''),
        ),
    ]
