# Generated by Django 2.2.6 on 2019-10-09 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0002_auto_20191009_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonsundayschool',
            name='title',
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='english_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='simplified_bible_verses',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='simplified_chinese_speaker',
            field=models.CharField(default='王宇辉传道', max_length=200),
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='simplified_chinese_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='tradition_bible_verses',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='tradition_chinese_speaker',
            field=models.CharField(default='王宇輝傳道', max_length=200),
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='tradition_chinese_title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='sermonsundayschool',
            name='bible_verses',
            field=models.CharField(default='', max_length=200),
        ),
    ]
