# Generated by Django 2.2.6 on 2019-10-09 04:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0003_auto_20191009_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermonsundayschool',
            name='upload_dt',
        ),
        migrations.AddField(
            model_name='sermonsundayschool',
            name='file_type',
            field=models.CharField(choices=[('Sermon', 'Sermon'), ('Sunday School', 'Sunday School')], default='Sermon', max_length=50),
        ),
        migrations.AlterField(
            model_name='sermonsundayschool',
            name='sermon_dt',
            field=models.DateField(default=datetime.date(2019, 10, 6), verbose_name='Sermon Date'),
        ),
    ]
