# Generated by Django 3.0.2 on 2020-01-19 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sermon', '0005_auto_20200119_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailybible',
            name='bible_verses',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='book',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='chapter',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Bible Date'),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='end_verse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='html',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='language',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='start_verse',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailybible',
            name='weekday',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
